svices:
  - type: web
    name: worker-api
    runtime: node
    buildCommand: pnpm install --frozen-lockfile && pnpm run build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /api/v1/auth/me
    disk:
      name: worker-db
      mountPath: /data
      sizeGB: 1
